# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from event.login_btn_events import LoginBtnEvents
from event.login_btn_events import GlobalObj


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        GlobalObj.main_window = LoginWindow
        GlobalObj.target = self

        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(321, 227)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.passwordLabel = QtWidgets.QLabel(self.centralwidget)
        self.passwordLabel.setGeometry(QtCore.QRect(70, 90, 60, 16))
        self.passwordLabel.setObjectName("passwordLabel")
        self.usernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.usernameLabel.setGeometry(QtCore.QRect(70, 50, 60, 16))
        self.usernameLabel.setObjectName("usernameLabel")
        self.usernameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameEdit.setGeometry(QtCore.QRect(130, 50, 113, 21))
        self.usernameEdit.setObjectName("usernameEdit")
        self.passwordEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordEdit.setGeometry(QtCore.QRect(130, 90, 113, 21))
        self.passwordEdit.setObjectName("passwordEdit")
        self.loginBtn = QtWidgets.QPushButton(self.centralwidget)
        self.loginBtn.setGeometry(QtCore.QRect(40, 150, 113, 32))
        self.loginBtn.setObjectName("loginBtn")
        self.registerBtn = QtWidgets.QPushButton(self.centralwidget)
        self.registerBtn.setGeometry(QtCore.QRect(160, 150, 113, 32))
        self.registerBtn.setObjectName("registerBtn")
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        self.loginBtn.clicked.connect(LoginBtnEvents.login_btn_event)
        self.registerBtn.clicked.connect(LoginBtnEvents.register_btn_event)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "登录"))
        self.passwordLabel.setText(_translate("LoginWindow", "密    码："))
        self.usernameLabel.setText(_translate("LoginWindow", "用户名："))
        self.loginBtn.setText(_translate("LoginWindow", "登录"))
        self.registerBtn.setText(_translate("LoginWindow", "注册"))
