# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from event.main_btn_events import MainBtnEvents, GlobalObj


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        GlobalObj.target = self

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(747, 554)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.analysePicBtn = QtWidgets.QPushButton(self.centralwidget)
        self.analysePicBtn.setGeometry(QtCore.QRect(27, 130, 120, 31))
        self.analysePicBtn.setObjectName("analysePicBtn")
        self.selectContractBtn = QtWidgets.QPushButton(self.centralwidget)
        self.selectContractBtn.setGeometry(QtCore.QRect(27, 70, 120, 31))
        self.selectContractBtn.setObjectName("selectContractBtn")
        self.infoTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.infoTextBrowser.setGeometry(QtCore.QRect(30, 230, 691, 291))
        self.infoTextBrowser.setMaximumSize(QtCore.QSize(800, 400))
        self.infoTextBrowser.setObjectName("infoTextBrowser")
        self.personalInfoBtn = QtWidgets.QPushButton(self.centralwidget)
        self.personalInfoBtn.setGeometry(QtCore.QRect(27, 190, 120, 31))
        self.personalInfoBtn.setObjectName("personalInfoBtn")
        self.testInfoBtn = QtWidgets.QPushButton(self.centralwidget)
        self.testInfoBtn.setGeometry(QtCore.QRect(27, 160, 120, 31))
        self.testInfoBtn.setObjectName("testInfoBtn")
        self.openMonitorBtn = QtWidgets.QPushButton(self.centralwidget)
        self.openMonitorBtn.setGeometry(QtCore.QRect(27, 100, 120, 31))
        self.openMonitorBtn.setObjectName("openMonitorBtn")
        self.openCameraBtn = QtWidgets.QPushButton(self.centralwidget)
        self.openCameraBtn.setEnabled(True)
        self.openCameraBtn.setGeometry(QtCore.QRect(27, 4, 120, 31))
        self.openCameraBtn.setObjectName("openCameraBtn")
        self.petKindSelect = QtWidgets.QComboBox(self.centralwidget)
        self.petKindSelect.setGeometry(QtCore.QRect(30, 40, 114, 21))
        self.petKindSelect.setObjectName("petKindSelect")
        self.petKindSelect.addItem("")
        self.petKindSelect.addItem("")
        self.petKindSelect.addItem("")
        self.cameraLabel = QtWidgets.QLabel(self.centralwidget)
        self.cameraLabel.setGeometry(QtCore.QRect(160, 10, 271, 201))
        self.cameraLabel.setAutoFillBackground(False)
        self.cameraLabel.setStyleSheet("border:1px solid black;")
        self.cameraLabel.setText("")
        self.cameraLabel.setObjectName("cameraLabel")
        self.picLabel = QtWidgets.QLabel(self.centralwidget)
        self.picLabel.setGeometry(QtCore.QRect(450, 10, 271, 201))
        self.picLabel.setStyleSheet("border:1px solid black;")
        self.picLabel.setText("")
        self.picLabel.setObjectName("picLabel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.openCameraBtn.clicked.connect(MainBtnEvents.open_camera_btn_event)
        self.selectContractBtn.clicked.connect(MainBtnEvents.select_contract_btn_event)
        self.openMonitorBtn.clicked.connect(MainBtnEvents.open_monitor_btn_event)
        self.analysePicBtn.clicked.connect(MainBtnEvents.analyse_pic_btn_event)
        self.testInfoBtn.clicked.connect(MainBtnEvents.test_info_btn_event)
        self.personalInfoBtn.clicked.connect(MainBtnEvents.personal_info_btn_event)
        self.petKindSelect.activated['QString'].connect(MainBtnEvents.pet_kind_btn_event)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.analysePicBtn.setText(_translate("MainWindow", "分析照片"))
        self.selectContractBtn.setText(_translate("MainWindow", "选择联系人"))
        self.personalInfoBtn.setText(_translate("MainWindow", "个人信息"))
        self.testInfoBtn.setText(_translate("MainWindow", "测试信息"))
        self.openMonitorBtn.setText(_translate("MainWindow", "开启实时监控"))
        self.openCameraBtn.setText(_translate("MainWindow", "开启摄像头"))
        self.petKindSelect.setItemText(0, _translate("MainWindow", "猫"))
        self.petKindSelect.setItemText(1, _translate("MainWindow", "狗"))
        self.petKindSelect.setItemText(2, _translate("MainWindow", "鼠"))
