# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from event.btn_events import BtnEvents


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(754, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.openCameraBtn = QtWidgets.QPushButton(self.centralwidget)
        self.openCameraBtn.setEnabled(True)
        self.openCameraBtn.setObjectName("openCameraBtn")
        self.gridLayout_2.addWidget(self.openCameraBtn, 0, 0, 1, 1)
        self.cameraView = QtWidgets.QGraphicsView(self.centralwidget)
        self.cameraView.setObjectName("cameraView")
        self.gridLayout_2.addWidget(self.cameraView, 0, 1, 7, 1)
        self.picView = QtWidgets.QGraphicsView(self.centralwidget)
        self.picView.setObjectName("picView")
        self.gridLayout_2.addWidget(self.picView, 0, 2, 7, 1)
        self.petKindSelect = QtWidgets.QComboBox(self.centralwidget)
        self.petKindSelect.setObjectName("petKindSelect")
        self.petKindSelect.addItem("")
        self.petKindSelect.addItem("")
        self.petKindSelect.addItem("")
        self.gridLayout_2.addWidget(self.petKindSelect, 1, 0, 1, 1)
        self.selectContractBtn = QtWidgets.QPushButton(self.centralwidget)
        self.selectContractBtn.setObjectName("selectContractBtn")
        self.gridLayout_2.addWidget(self.selectContractBtn, 2, 0, 1, 1)
        self.openMonitorBtn = QtWidgets.QPushButton(self.centralwidget)
        self.openMonitorBtn.setObjectName("openMonitorBtn")
        self.gridLayout_2.addWidget(self.openMonitorBtn, 3, 0, 1, 1)
        self.analysePicBtn = QtWidgets.QPushButton(self.centralwidget)
        self.analysePicBtn.setObjectName("analysePicBtn")
        self.gridLayout_2.addWidget(self.analysePicBtn, 4, 0, 1, 1)
        self.testInfoBtn = QtWidgets.QPushButton(self.centralwidget)
        self.testInfoBtn.setObjectName("testInfoBtn")
        self.gridLayout_2.addWidget(self.testInfoBtn, 5, 0, 1, 1)
        self.personalInfoBtn = QtWidgets.QPushButton(self.centralwidget)
        self.personalInfoBtn.setObjectName("personalInfoBtn")
        self.gridLayout_2.addWidget(self.personalInfoBtn, 6, 0, 1, 1)
        self.infoTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.infoTextBrowser.setMaximumSize(QtCore.QSize(800, 400))
        self.infoTextBrowser.setObjectName("infoTextBrowser")
        self.gridLayout_2.addWidget(self.infoTextBrowser, 7, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.openCameraBtn.clicked.connect(BtnEvents.open_camera_btn_event)
        self.selectContractBtn.clicked.connect(BtnEvents.select_contract_btn_event)
        self.openMonitorBtn.clicked.connect(BtnEvents.open_monitor_btn_event)
        self.analysePicBtn.clicked.connect(BtnEvents.analyse_pic_btn_event)
        self.testInfoBtn.clicked.connect(BtnEvents.test_info_btn_event)
        self.personalInfoBtn.clicked.connect(BtnEvents.personal_info_btn_event)
        self.petKindSelect.activated['QString'].connect(BtnEvents.pet_kind_btn_event)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openCameraBtn.setText(_translate("MainWindow", "开启摄像头"))
        self.petKindSelect.setItemText(0, _translate("MainWindow", "猫"))
        self.petKindSelect.setItemText(1, _translate("MainWindow", "狗"))
        self.petKindSelect.setItemText(2, _translate("MainWindow", "鼠"))
        self.selectContractBtn.setText(_translate("MainWindow", "选择联系人"))
        self.openMonitorBtn.setText(_translate("MainWindow", "开启实时监控"))
        self.analysePicBtn.setText(_translate("MainWindow", "分析照片"))
        self.testInfoBtn.setText(_translate("MainWindow", "测试信息"))
        self.personalInfoBtn.setText(_translate("MainWindow", "个人信息"))
