# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from event.register_btn_events import GlobalObj, RegisterBtnEvents


class Ui_RegisterWindow(object):
    def set_login_view(self, login_view):
        self.login_view = login_view
        GlobalObj.login_view = login_view

    def setupUi(self, RegisterWindow):
        GlobalObj.target = self
        GlobalObj.main_window = RegisterWindow

        RegisterWindow.setObjectName("RegisterWindow")
        RegisterWindow.resize(321, 228)
        self.centralwidget = QtWidgets.QWidget(RegisterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.usernameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameEdit.setGeometry(QtCore.QRect(140, 40, 113, 21))
        self.usernameEdit.setObjectName("usernameEdit")
        self.passwordLabel = QtWidgets.QLabel(self.centralwidget)
        self.passwordLabel.setGeometry(QtCore.QRect(70, 80, 60, 16))
        self.passwordLabel.setObjectName("passwordLabel")
        self.passwordEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordEdit.setGeometry(QtCore.QRect(140, 80, 113, 21))
        self.passwordEdit.setObjectName("passwordEdit")
        self.usernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.usernameLabel.setGeometry(QtCore.QRect(70, 40, 60, 16))
        self.usernameLabel.setObjectName("usernameLabel")
        self.rePasswordEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.rePasswordEdit.setGeometry(QtCore.QRect(140, 120, 113, 21))
        self.rePasswordEdit.setObjectName("rePasswordEdit")
        self.rePasswordLabel = QtWidgets.QLabel(self.centralwidget)
        self.rePasswordLabel.setGeometry(QtCore.QRect(70, 120, 60, 16))
        self.rePasswordLabel.setObjectName("rePasswordLabel")
        self.registerBtn = QtWidgets.QPushButton(self.centralwidget)
        self.registerBtn.setGeometry(QtCore.QRect(100, 160, 113, 32))
        self.registerBtn.setObjectName("registerBtn")
        RegisterWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RegisterWindow)
        self.registerBtn.clicked.connect(RegisterBtnEvents.register_btn_event)
        QtCore.QMetaObject.connectSlotsByName(RegisterWindow)

    def retranslateUi(self, RegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        RegisterWindow.setWindowTitle(_translate("RegisterWindow", "注册"))
        self.passwordLabel.setText(_translate("RegisterWindow", "密      码："))
        self.usernameLabel.setText(_translate("RegisterWindow", "用  户  名："))
        self.rePasswordLabel.setText(_translate("RegisterWindow", "确认密码："))
        self.registerBtn.setText(_translate("RegisterWindow", "注册"))
